// GENERATED by scripts/gen-blur-placeholders.mjs. Do not edit by hand.
export const BLUR: Record<string, string> = {
  "/images/reports/insect-proteins.webp": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoQAAoAA4BaJYgCdADQw6/SAAD8bodz9DqAgk+P3pyWvqIKJsZfay9hIoatw+DZHN+c7KvTXMAAAA==",
  "/images/reports/petcare-market.webp": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwAQCdASoQAAoAA4BaJYgCdAYs3kfwzLAA+WfnMTozmFcQ/tcp7ICslruOuU9KuVdzL7RJEneUlbnlVc84E0YbkwQi51CleFgXDUPMRrLLsP9eBtTdXeLX6NPzGhhfcOcc3sFoZNAogJMAAAA=",
  "/images/reports/vegan-palatants.webp": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAoAA4BaJQBdgB4g76Whp2AA/spp0n3JQAOwFKS2xBYIxH5VvWMET8s5XkyR3c8MLxqY1A4VvoK4spj0qVTRBLcAAA==",
  "/images/reports/vegan-petfood.webp": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAoAA4BaJZACdAD7zDSS1MAAAP7ybI77dpljj97K0n4MNDWVhNYa7rx8JEdHYZBRVbV8bw6VcnrmfGbFFUGPIJAb9vdVTUMhXJgA",
  "/images/blog/alternative-protein-failures.webp": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAwAgCdASoQAAwAA4BaJZwAD5DsjrVMNuKxQAD+88jdlca5EeU0COpx6dubBB+yG20hjat2Wnsz80LVZDQkyQF1Ttb6bJ0otDkbAkb+M8xRN+As3//AjOlAhkUdnXMz+0kMqnjXWAA=",
  "/images/blog/bond-hills.webp": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAsAA4BaJZQCdAYuRwRVvngAAP7oSM0Yog8GqgmDskzfwkACC56tbg7RhjKs2JU80VT2uJAMf5hI5hAlQ+gZGOxl3Bz+1kAAAA==",
  "/images/blog/business-model.webp": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoQAAoAA4BaJZQAAueH0jmAAP7t7V38bze/tvXziqGOYcNBe4NB1uDI5NIeXzsIQAXKAAAA",
  "/images/blog/coolty-meat.webp": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbAC7ABjcYDy1mdVU/7vD0gAA/sN0/HiSgcjcD38sjFGbMgTAAx+SDncGQpIWQCgrCR8+FP3cobBojBCSODWVxTk3QdrqcTIzIWlWdWYnRmPcuA2U3XhIA/az7iCBa1jL5cHR/ZF4gAAA",
  "/images/blog/enifer-stand.webp": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYwCdAYw67QUhvcvxjQ+eR96AAMxU3IHRyTSnEgwmLIhv7OFVoDD7+nKjgZiId1UCCE7csDIj+0PiIfYlsJD0mzB8sAhNNuMAR3UfXogAY/gCfHV16X1/WyCz6pdIFdnTA35kFNbMxnbeAgcmXBA5Embb1DxEEVnl/IyMAAA=",
  "/images/blog/fifa-world-cup-lessons.webp": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoQAAoAA4BaJbACdAEedNlCD3DYAP70mDFbpWps+YZwRmskl1+SlpYxi9zgWnsnKdVd58Bht/3tiiERXAAAAA==",
  "/images/blog/interzoo-2026.webp": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAoAA4BaJZAAD5LQ2s93S0NIAP6tXTht+m8wIhEaTDM7cD/OGZpVlHWz6lmdmLGutwqAgfazTDWwuiMCnPvIEgXMdyclbHxM+ob6RMD9fexkJDIghxAA",
  "/images/blog/petfood-palatability-fat-is-the-signal.webp": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAAAQAgCdASoQAAkAA4BaJZQCdAEPBYRO77AAAP72JYr/R8STzX38EzPAaxbtrRuFQAA=",
  "/images/blog/petfood-palatability-fresh-kill-signal.webp": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAQCdASoQAAkAA4BaJZQE6AhwBZgAAP7xMoMPHAJ/7enrAVr+NVM0JnZAAA==",
  "/images/blog/petfood-palatability-replacing-meat.webp": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAQAgCdASoQAAkAA4BaJZQCdAEUpRcRvVwAAP7zzufUxrTN+aaVkuVbvrXRUuvaKg269reb96a5jSbcZxAAAA==",
  "/images/blog/republica-2025-diaspora.webp": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABQAgCdASoQAAsAA4BaJbACdDiAByVGB1uMzAAA/uz8jyh+MkF8Zg1jXPj+77N8LBhRmkDwrKIDugtHGLFujMtpQ6yVgH+S78bx97W/XmnJy/M7QGw5NWc4Qw9Bjl9peLS+JFOdJxTbFUAA",
  "/images/stories/bsf-startup-testimony.webp": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAgCdASoQAAwAA4BaJYgCdAEUo3yFEcggAP7s+J1dhg3fa8j+pcMd7alu/yfJa+gT/DSKlNJRoAY8uhp85yjm6uvO92g8AAA=",
  "/images/stories/kiambu-bsf.webp": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA4BaJbACdAEXdftJ29AA/qZ+ChpRpoX5htUK67qZcQ2A8AM9gVLEo1CC7dhrI434DS02f6xMYuJ+yx27pY5/ysEQAAA=",
  "/images/stories/smart-farm-bsf.webp": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwAgCdASoQAAkAA4BaJbACdAEWz8KIaZ+TwAD2vBs0eTfTFvQA/ZXbkVsvcpWpqA/x8R+m9MAMAYYfl9dKPKtnkm1Qr6hNww91Q3I2PM+gS3e9d78YP+kfBL6UepYAAAA="
};
